### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by marcotroisi** [mossphp/moss-framework#24]
Documentation could be improved, I think:

1. Use Github Markdown with coloured syntax for code (it's makes it easier to read)
2. Router Configurations in the bootstrap file are in *Config* and not in *Router*; while that may make sense, it's not immediately obvious when looking for how to configure Router options
3. Perhaps moving all the docs in Github wiki or some platform where things can also be easily searched for.

Thanks and keep up the good work!

**Comment by potfur** [comment]
Its being ported to wiki right now.
But if you want to contribute/improve - you are welcome.
