### ISSUE TITLE
xdebug error

### ISSUE THREAD

**Issue by andrewprofile** [mossphp/moss-framework#25]
Bład pojawił się podczas testowania moss-demo-app, bo nie mam xdebuga. 
`Fatal error: Call to undefined function Moss\Kernel\xdebug_var_dump() in ...\Moss\Kernel\ExceptionHandler.php on line 179`

Naprawiłem to tak:
```
if (extension_loaded('xdebug')) {
    xdebug_var_dump($var);
} else {
    echo '<pre>'.print_r($var,true).'</pre>';
}
````

**Comment by potfur** [comment]
Dzięki.
Poprawione w dev 1c98b53fd715736141ceeebe7d7a1a99e90fc024

**Comment by andrewprofile** [comment]
Jeszcze do ErrorHandler rzucasz zmienna $display która nic nie robi i przydało by się kiedy wyłączysz raportowanie błędów to żeby z wyjątków nie rzucało numerem lini błędu tylko samym komunikatem. No i level oraz detail nie idą ze sobą w parze bo daje level na 0 a tam nie ustawie na false to itak dostaje tryb debug :)

**Comment by potfur** [comment]
Dzięki za przypomnienie od zagubionym `display` został usunięty z handlera i z konfiguracji.

Nie muszą iść w parze. `level` określa jakie błędy są raportowane, zaś `detail` w jaki sposób.

**Comment by andrewprofile** [comment]
Ja rozumiem, ale kiedy ustawiam na 0 to teoretycznie wyłączam ich wyświetlanie, a wyjątki dalej wyświetlają wszystko. Przydało by się po prostu takie rozróżnienie miedzy trybem dev a produkcyjnym jak jest chociażby w symfony :) bo dla Ciebie to jest może intuicyjne, że musisz tu dać na 0 tam na false ale dla kogoś z zewnątrz już nie do końca :)

**Comment by potfur** [comment]
`ErrorHandler` nie jest po to by pokazywać/ukrywać błędy, jeno po to by zamieniać pewne ich grupy (domyślnie wszystkie) na wyjątki.

Jeśli chcesz mieć tryb _deweloperski_ to proponuję coś takiego - `import_dev` będzie importowany gdy `$mode === 'dev'`.

```php
    $config = [
        'framework' => [
            'error' => [ 'level' => 0, 'detail' => false ],
        ],
        'import_dev' => [
            'framework' => [
                'error' => [ 'level' => -1, 'detail' => true ],
            ],
        ]
    ];

    $mode = getenv('APP_DEV') ? 'dev' : null;

    $app = new App(new Config($config, $mode));
```

Wg mnie rozwiązanie dużo bardziej wygodne - że o podpięciu odpowiedniej obsługi pod `error.*` na produkcji nie wspomnę

**Comment by andrewprofile** [comment]
Ja rozumiem poco jest ErrorHandler, o właśnie o to mi chodziło :) Tyle, że aż tak się nie zagłębiłem w Twojego frameworka, żeby dojść do takiego rozwiązania. Przeczyłem to na wiki :)

**Comment by potfur** [comment]
No to zamykamy.;
